apiVersion: v1
kind: ServiceAccount
metadata:
  name: skaffold
---
# https://kubernetes.io/zh-cn/docs/reference/access-authn-authz/rbac/#role-and-clusterole
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: skaffold-example-role
rules:
  - apiGroups: [""] # 空字符串"" 表明使用 core API group
    resources: ["pods","nodes"]
    verbs: ["get", "watch", "list"]

---
# Path: k8s/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: skaffold-example-rolebinding
subjects:
- kind: User    # 这里使用的是用户
  name: skaffold   # 用户名
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" 指定与某 Role 或 ClusterRole 的绑定关系
  kind: Role  # 此字段必须是 Role 或 ClusterRole
  name: skaffold-example-role  # 此字段必须与你要绑定的 Role 或 ClusterRole 的名称匹配
  apiGroup: rbac.authorization.k8s.io